### ISSUE TITLE
How can I archive ALL files from within cwd?

### ISSUE THREAD

**Issue by dav-tb** [a7ul/tar-action#16]
Hello,

First, thanks for writing this action.

I tried running it with the following settings:

```yaml
- name: Compress build to TAR archive
  uses: a7ul/tar-action@v1.1.0
  with:
    command: c
    cwd: ./site
    files: "**/*.*"
    outPath: site.tar.gz
```

Unfortunately, glob patterns don't seem to be supported.

I have also tried *not* providing the `files` argument, hoping maybe it would just assume it must archive everything, but as stated in documentation, it is a required argument and therefore it doesn't work.

Is there an easy way to tell the action to archive all files and directories within the current working directory? At this point the only other way I can think of is running a `find . -type f` command prior to the action and set the result into an array variable. I'm not sure how to do that with GitHub Actions - or if it can be done at all.

Any insight would help a lot.

**Comment by meilechwieder** [comment]
Any answer on this?

**Comment by wout** [comment]
FWIW:

```yaml
- name: Compress files into .tar
  uses: a7ul/tar-action@v1.1.0
  with:
    command: c
    cwd: ./
    files: ./
    outPath: deploy.tar
```
